### ISSUE TITLE
multi-site crash

### ISSUE THREAD

**Issue by mikestemple** [gedex/wp-slack#29] opened 2015-01-15 13:25 UTC
When activating on a multi-site install at the network level (for all sites) it crashes the wp-admin (white screens).

**Comment by gedex** [comment] 2015-10-22 00:54
@mikestemple I couldn't reproduce the issue.

Here's my multi-site test env:

* Part of `wp-config.php` that relevant to network setup:

  ~~~php
  define('MULTISITE', true);
  define('SUBDOMAIN_INSTALL', true);
  define('DOMAIN_CURRENT_SITE', 'local.wpmu.dev');
  define('PATH_CURRENT_SITE', '/');
  define('SITE_ID_CURRENT_SITE', 1);
  define('BLOG_ID_CURRENT_SITE', 1);
  ~~~

* I've four sites with Slack plugin being network-activated (quite fresh plugins):

  ![screen shot 2015-10-22 at 7 47 02 am](https://cloud.githubusercontent.com/assets/78313/10654218/b17176de-7891-11e5-885b-0dc4ba784f77.png)

* Added integration on each site and test each of them without issue.

I'll close and mark this is as `wontfix`. I suggest you to try disable plugin one-by-one and report it with detailed steps if issue persists.

**Closed by gedex** 2015-10-22 00:54 UTC
Labels: wontfix
